logging:
  level:
    root: INFO
    dev.mbo: TRACE
    org:
      springframework:
        security: DEBUG
  pattern:
    # pattern for including MDC
    console: ${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%15.15t]){faint} [%logger] %clr(%F:%L){cyan} %clr(:){faint} %m %clr({){faint}%X%clr(}){faint}%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}

spring:
  data:
    redis:
      host: localhost
      port: 6379
      username: TODO
      password: TODO
  jackson:
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
      FAIL_ON_INVALID_SUBTYPE: false
    serialization:
      INDENT_OUTPUT: false
      ORDER_MAP_ENTRIES_BY_KEYS: true
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_EMPTY_JSON_ARRAYS: false
      WRITE_ENUMS_USING_TO_STRING: true
      WRITE_NULL_MAP_VALUES: false
      WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED: false
      FAIL_ON_SELF_REFERENCES: true
    default-property-inclusion: non_null
    time-zone: UTC
  profiles:
    active: secure

app:
  redis:
    url:
      key:
        prefix: "u:"
    user:
      key:
        prefix: "c:"
      admin:
        username: TODO
        password: TODO